"""replace position with x,y coordinates

Revision ID: 62e832763a1f
Revises: 91d3009a0b47
Create Date: 2025-04-12 20:53:49.627094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e832763a1f'
down_revision: Union[str, None] = '91d3009a0b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('y', sa.Integer(), nullable=True))
    op.drop_column('habits', 'position')
    op.add_column('identities', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('identities', sa.Column('y', sa.Integer(), nullable=True))
    op.drop_column('identities', 'position')
    op.add_column('skills', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('y', sa.Integer(), nullable=True))
    op.drop_column('skills', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('position', sa.INTEGER(), nullable=True))
    op.drop_column('skills', 'y')
    op.drop_column('skills', 'x')
    op.add_column('identities', sa.Column('position', sa.INTEGER(), nullable=True))
    op.drop_column('identities', 'y')
    op.drop_column('identities', 'x')
    op.add_column('habits', sa.Column('position', sa.INTEGER(), nullable=True))
    op.drop_column('habits', 'y')
    op.drop_column('habits', 'x')
    # ### end Alembic commands ###
