"""add position fields

Revision ID: 91d3009a0b47
Revises: f6d91ad0ea23
Create Date: 2025-04-12 04:43:40.189428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d3009a0b47'
down_revision: Union[str, None] = 'f6d91ad0ea23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('identities', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'position')
    op.drop_column('identities', 'position')
    op.drop_column('habits', 'position')
    # ### end Alembic commands ###
